site_name: Polar to WGS84 Converter
site_url: https://pdssp.pages.cnes.fr/common/polar2wgs84
repo_url: https://gitlab.cnes.fr/pdssp/common/polar2wgs84
repo_name: polar2wgs84
theme:
  name: material
  language: en
  logo: images/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Content:
      - History: history.md
      - Introduction: introduction.md
      - Applicable Documents: applicable_docs.md
      - Glossary: glossary.md
      - Conventions: conventions.md
      - Purpose: purpose.md
      - External View: external_view.md
      - Operations Environment: operations_environment.md
      - Operations Basics: operations_basics.md
      - Operation Manual: operation_manual.md
      - Reference Manual: reference_manual.md
      - Tutorial: generated/gallery
  - Tests results: report.html
  - Tests coverage: _static/coverage/index.html
  - Legal : legal.md
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - gallery:
      examples_dirs: docs/examples          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
  - search
  - macros:
      modules:
        - macros.macros
  - with-pdf:
      author: Jean-Christophe Malapert
      copyright: "\xA9 2025 CNES"
      cover: true
      cover_title: Polar to WGS84 Converter documentation
      cover_subtitle: Version Version {{ package_version }}
      output_path: docs/polar2wgs84.pdf
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: false
            show_root_full_path: false
            show_root_members_full_path: false
            show_signature: true
            show_signature_annotations: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_attributes: true
            show_docstring_parameters: true
            show_docstring_returns: true
            show_docstring_raises: true
